python3 -m piper_train \
    --dataset-dir ./target_voice_dataset/ \
    --accelerator gpu \
    --devices 1 \
    --batch-size 8 \
    --validation-split 0.0 \
    --num-test-examples 0 \
    --max_epochs 30000 \
    --resume_from_checkpoint ./pretrained_tts_checkpoint/*.ckpt \
    --checkpoint-epochs 1 \
    --precision 32
